#include "Customer\!Customer.sql"
#include "Rollout\!Rollout.sql"

#include "dbo.usp_Word_All_Get.sql"
#include "dbo.usp_Word_Merge.sql"
#include "dbo.usp_Word_Learned_Mark.sql"
#include "dbo.usp_Word_Sound_Add.sql"
#include "dbo.usp_Word_Sound_Get.sql"
#include "dbo.usp_Word_Translation_Save.sql"
#include "dbo.usp_Log_Add.sql"