#include "Customer\!Customer.sql"
#include "Rollout\!Rollout.sql"

#include "dbo.usp_Word_All_Get.sql"
#include "dbo.usp_Phrase_Merge.sql"
#include "dbo.usp_Word_Learned_Set.sql"
#include "dbo.usp_Word_Sound_Add.sql"
#include "dbo.usp_Word_Sound_Get.sql"
#include "dbo.usp_Word_Translation_Save.sql"
#include "dbo.usp_Log_Add.sql"
#include "dbo.usp_Movie_Get.sql"
#include "dbo.usp_Language_Get.sql"
#include "dbo.usp_Movie_Delete.sql"
#include "dbo.usp_Movie_Rename.sql"
#include "dbo.usp_Movie_Archive_Set.sql"

#include "dbo.usp_CustomerState_Update.sql"
#include "dbo.usp_CustomerState_Get.sql"
#include "dbo.usp_Phrase_Get.sql"