#include "dbo.usp_Customer_Create.sql"
#include "dbo.usp_Customer_Get.sql"
#include "dbo.usp_Customer_Password_Update.sql"
#include "dbo.usp_Customer_RestoreCode_Get.sql"
#include "dbo.usp_Customer_RestoreCode_Verify.sql"
#include "dbo.usp_Customer_Setting_Get.sql"
#include "dbo.usp_Customer_Setting_Update.sql"
#include "dbo.usp_Customer_Unblock.sql"