#include "dbo.usp_Customer_Create.sql"
#include "dbo.usp_Customer_Get.sql"
#include "dbo.usp_Customer_Password_Update.sql"
#include "dbo.usp_Customer_Save.sql"
#include "dbo.usp_Customer_RestoreCode_Get.sql"